### ISSUE TITLE
Failed to clone due to lfs failed to download libnvinfer.so.7.9.0.gz

### ISSUE THREAD

**Issue by lenLRX** [mlcommons/inference_results_v0.7#14]
When I tried to clone the repo, I got the following error:
Is that possible to fix this problem? Maybe some lfs obj should be pushed again?

```bash
git clone https://github.com/mlcommons/inference_results_v0.7.git
Cloning into 'inference_results_v0.7'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 32799 (delta 4), reused 8 (delta 3), pack-reused 32782
Receiving objects: 100% (32799/32799), 205.18 MiB | 1.62 MiB/s, done.
Resolving deltas: 100% (12685/12685), done.
Updating files: 100% (31842/31842), done.
Downloading open/NVIDIA/code/bert/tensorrt_sparse/TensorRT-preview/lib/libnvinfer.so.7.9.0.gz (103 MB)
Error downloading object: open/NVIDIA/code/bert/tensorrt_sparse/TensorRT-preview/lib/libnvinfer.so.7.9.0.gz (24242fe): Smudge error: Error downloading open/NVIDIA/code/bert/tensorrt_sparse/TensorRT-preview/lib/libnvinfer.so.7.9.0.gz (24242fed821ce54a53513cd02c5f4987d5eeb7864171af988798f9c62bd7a161): [24242fed821ce54a53513cd02c5f4987d5eeb7864171af988798f9c62bd7a161] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to /data/inference_results_v0.7/.git/lfs/logs/20210128T222321.198206086.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: open/NVIDIA/code/bert/tensorrt_sparse/TensorRT-preview/lib/libnvinfer.so.7.9.0.gz: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by nvpohanh** [comment]
@lenLRX If you do `git clone https://github.com/mlperf/inference_results_v0.7.git` instead, does it work?

**Comment by lenLRX** [comment]
> @lenLRX If you do `git clone https://github.com/mlperf/inference_results_v0.7.git` instead, does it work?

I just tried to clone from this address `git clone https://github.com/mlperf/inference_results_v0.7.git` and got the same error as mlcommon repo

**Comment by nvpohanh** [comment]
Could you then try `GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/mlcommons/inference_results_v0.7.git`?

@guschmue seems that the Git-LFS has some issue?

**Comment by lenLRX** [comment]
> Could you then try `GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/mlcommons/inference_results_v0.7.git`?
> 
> @guschmue seems that the Git-LFS has some issue?

It fixes the clone issue, but `git lfs pull`    still failed. 
I am looking for downloading the libnvifo. so

**Comment by nvpohanh** [comment]
I see. @guschmue What would be a good way we fix this? It would be quite bad that someone can't even clone this repo.

I have the build locally. Is there a way I can push to Git-LFS server directly? 🤔

**Comment by guschmue** [comment]
Hm, I didn't realize that lfs was involved. Thought that would require some setup which we didn't do. 
Let me look at it.

**Comment by lenLRX** [comment]
> Hm, I didn't realize that lfs was involved. Thought that would require some setup which we didn't do.
> Let me look at it.

Any idea to fix it?
Maybe an PR from @nvpohanh can fix? Or it has to be someone with the write access to this repo to upload the lfs object?

**Comment by nvpohanh** [comment]
@guschmue Could you do the following?

- Clone the repo with `GIT_LFS_SKIP_SMUDGE=1`
- Download [the file](https://drive.google.com/file/d/1d43A5CXLpQh3c1lDg-zowaIdm1_PQOW7/view?usp=sharing)
- Put it at `open/NVIDIA/code/bert/tensorrt_sparse/TensorRT-preview/lib/libnvinfer.so.7.9.0.gz`
- `git add open/NVIDIA/code/bert/tensorrt_sparse/TensorRT-preview/lib/libnvinfer.so.7.9.0.gz`
- `git lfs push origin master`

Thanks

**Comment by guschmue** [comment]
just tried but it doesn't push anything, I think it does know about the file already.
git lfs ls-files -s shows
24242fed82 - open/NVIDIA/code/bert/tensorrt_sparse/TensorRT-preview/lib/libnvinfer.so.7.9.0.gz (103 MB)

**Comment by nvpohanh** [comment]
@guschmue Could you try some of these options? Thanks

https://stackoverflow.com/questions/35049603/git-lfs-files-not-found-on-server
https://stackoverflow.com/questions/62852772/error-when-getting-git-lfs-files-object-does-not-exist-on-the-server-404-obj
